name: dailynews24
description: Daily News 24 is one of Nigeria's fastest growing independent online news platform

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  easy_debounce: ^2.0.3
  http: ^1.0.0
  google_fonts: ^4.0.5
  jiffy: ^6.1.0
  loadmore: ^2.1.0
  fluttertoast: ^8.2.2
  skeletons: ^0.0.3
  url_launcher: ^6.2.2
  connectivity_plus: ^4.0.1
  flutter_bloc: ^8.1.3
  json_annotation: ^4.7.0
  intl: ^0.18.0
  freezed_annotation: ^2.2.0
  flutter_html: ^3.0.0-beta.2
  gap: ^3.0.1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_native_splash:
  color: "#c4302b"
  image: "assets/images/logo.png"
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
